### ISSUE TITLE
Package assumes install of npm (does not allow yarn instead)

### ISSUE THREAD

**Issue by phantomjinx** [ds300/postinstall-postinstall#2]
Our project is using _yarn_ and as such our CircleCI builds do not even have _npm_ installed. Therefore, when installing and configuring [patch-package](https://github.com/ds300/patch-package), the build server errors even though patch-package is executed with --use-yarn.

```[ERROR] Directory: /workspace/app/ui/node_modules/postinstall-postinstall
[ERROR] Output:
[ERROR] /bin/sh: 1: npm: not found
[ERROR] child_process.js:644
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Command failed: npm run prepare
[ERROR] /bin/sh: 1: npm: not found
[ERROR] 
[ERROR]     at checkExecSyncError (child_process.js:601:13)
[ERROR]     at execSync (child_process.js:641:13)
[ERROR]     at Object.<anonymous> (/workspace/app/ui/node_modules/postinstall-postinstall/run.js:14:5)
[ERROR]     at Module._compile (module.js:652:30)
[ERROR]     at Object.Module._extensions..js (module.js:663:10)
[ERROR]     at Module.load (module.js:565:32)
[ERROR]     at tryModuleLoad (module.js:505:12)
[ERROR]     at Function.Module._load (module.js:497:3)
[ERROR]     at Function.Module.runMain (module.js:693:10)
[ERROR]     at startup (bootstrap_node.js:191:16)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.503 s
[INFO] Finished at: 2018-10-18T15:43:04Z
[INFO] Final Memory: 31M/102M
```
Looking at run.js, postinstall-postinstall (as well as postinstall-prepare) assume _npm_ but neither have facility for using _yarn_ instead.

**Comment by ds300** [comment]
Oh yeah that makes sense. postinstall-postinstall should only be useful for yarn-based workflows anyway, so I just changed it to yarn and published `postinstall-postinstall@2.0.0`.

Thanks for the report!
