### ISSUE TITLE
Command failed with exit code 1. (checkExecSyncError)

### ISSUE THREAD

**Issue by osrl** [ds300/postinstall-postinstall#7]
Here is the log I get when I try to run `yarn install`, `yarn add` or `node ./node_modules/postinstall-postinstall/run.js`:

I've tried to debug this and I've found out that spawnSync inside `checkExecSyncError` returns an error. This causes `checkExecSyncError` to return an error also. Workaround is replacing `execSync` with `exec`.
```
error ****/node_modules/postinstall-postinstall: Command failed.
Exit code: 1
Command: node ./run.js
Arguments:
Directory: ****/node_modules/postinstall-postinstall
Output:
error Command failed with exit code 1.
child_process.js:660
    throw err;
    ^

Error: Command failed: yarn run postinstall
error Command failed with exit code 1.

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (****/node_modules/postinstall-postinstall/run.js:14:5)
```

**Comment by wildanzulkarnaen** [comment]
same here

error /xxxx/react-native/node_modules/postinstall-postinstall: Command failed.
Exit code: 1
Command: node ./run.js
Arguments: 
Directory: /xxxx/react-native/node_modules/postinstall-postinstall
Output:
error Command failed with exit code 1.
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn run postinstall
error Command failed with exit code 1.`

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (/xxxx/react-native/node_modules/postinstall-postinstall/run.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

Using
`yarn 1.22.4`
`node v10.20.1`

**Comment by welljsjs** [comment]
@ds300 Hi there, sorry for waking you up, this is currently causing us a little headache - is there anything you can do about it? 

It's pretty difficult for us to patch it without having to maintain our own version of the package (since any patches using the [`patch-package`](https://www.npmjs.com/package/patch-package) dependency rely on this package).

**Comment by 2xAA** [comment]
@welljsjs - is https://github.com/simply-vat/postinstall-postinstall a stable fix?

**Comment by welljsjs** [comment]
It's fixed the issue for us @2xAA and we haven't had any problems with it IIRC
this is the important change: https://github.com/simply-vat/postinstall-postinstall/commit/59b0064272e72ab62eab205d6c63e7e60495b097#diff-f37164ed621e6f1db870a6fa99420258869ae02f4e9d0a3de9e75a5d7910065cR4

**Comment by s0ber** [comment]
@ds300 it's hurting our project as well, please take a look if you'll have a chance

**Comment by Nantris** [comment]
@ds300 it would be great if this issue could get fixed. We've been using `patch-package` without issue on Linux, but it's failing for us on Windows.

It's sort of strange that `postinstall-postinstall` is neglected when your wildly popular `patch-package` depends on it. Now I'm not sure how to proceed.

**Comment by Nantris** [comment]
@ds300 friendly bump - the changes look very minimal - just changing `require('child_process').execSync` to `require('child_process').exec` I would submit a PR if you can confirm your willingness to accept it.

https://github.com/simply-vat/postinstall-postinstall/commit/59b0064272e72ab62eab205d6c63e7e60495b097#diff-f37164ed621e6f1db870a6fa99420258869ae02f4e9d0a3de9e75a5d7910065cR4

**Comment by reeywhaar** [comment]
@Slapbox @junipera, using exec succeeds because exec requires callback, it is async. You just ignore error and output when changing to exec. Also you break shouldUseYarn function as it will succeed every time.

**Comment by sivakusayan** [comment]
It seems like the real error is being swallowed for some reason. When I got this error running patch-packages in our CI, it was because a patch failed to be applied as the patch was considered invalid. 

Fixing the patch error also fixed this error.

**Comment by Nantris** [comment]
@sivakusayan are you still seeing this with `8.x`? I don't recall having seen this for some time now.

**Comment by sivakusayan** [comment]
@Slapbox I never got this problem locally, only when running the package in some Linux box for our CI (that I'm admittedly not too familiar with the set up for).

It happened when we upgraded to Node 18, along with bumping the versions of a bunch of dependencies.

**Comment by karel-suchomel-ed** [comment]
I'm having the same issue

 "patch-package": "^8.0.0"
 "postinstall-postinstall": "^2.1.0"

**Comment by karel-suchomel-ed** [comment]
I was having the same issue, but it was caused by some no longer needed patch files, that I forgot to remove.

**Comment by ianyoung** [comment]
What's the latest with this issue? Is there a recommended approach to getting around it?

The above fork seems to now be deprecated:
https://github.com/simply-vat/postinstall-postinstall

**Comment by rada** [comment]
> @Slapbox I never got this problem locally, only when running the package in some Linux box for our CI (that I'm admittedly not too familiar with the set up for).
> 
> It happened when we upgraded to Node 18, along with bumping the versions of a bunch of dependencies.

Were you able to resolve it? We're having the same problem after upgrading Node to 18 (from 16). The postinstall fails only in CI however sometimes it succeeds and sometimes fails. Strange.

**Comment by ianyoung** [comment]
For me it was also an issue as part of the CI/CD process running Node.js 18. 

It looks like this package has long been abandoned with no notable activity in 5+ years and this issue open for since 2019. I was lucky to be able to patch the issue I needed `postinstall` for at source but for other cases I would suggest using another package.
